-- 0001_core.sql — Sodalitas federation core.
--
-- Conventions used throughout every migration:
--   * IDs are prefixed random tokens (TEXT). Generated by domain/ids.ts, never by SQLite.
--   * Timestamps are TEXT ISO-8601 UTC ("2026-08-03T14:00:00.000Z") — sorts lexicographically.
--   * Calendar dates are TEXT "YYYY-MM-DD" (a meeting is on a day, not at an instant).
--   * Money is INTEGER cents. Never a float, anywhere, for any reason.
--   * Booleans are INTEGER 0/1.
--   * Every tenant-owned table carries tenant_id and is indexed on it FIRST.
--
-- D1 has no row-level security. The tenant boundary is enforced in db/scope.ts,
-- which is the only sanctioned way to reach these tables. A raw DB.prepare()
-- against a tenant-owned table is a bug.

-- ── Tenancy ───────────────────────────────────────────────────────────────────
-- A tenant is the billing + ownership boundary: either a district (which owns
-- many clubs) or a single club that pays for itself. Clubs belong to exactly one
-- tenant. This is what lets a district buy the platform for its clubs without
-- taking their autonomy away.
CREATE TABLE tenants (
  id            TEXT PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  kind          TEXT NOT NULL DEFAULT 'club',      -- 'club' | 'district'
  plan_key      TEXT NOT NULL DEFAULT 'club_starter',
  status        TEXT NOT NULL DEFAULT 'active',    -- active | paused | cancelled
  is_demo       INTEGER NOT NULL DEFAULT 0,
  timezone      TEXT NOT NULL DEFAULT 'America/Chicago',
  country_code  TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_tenants_status ON tenants(status);

-- Login identities. A user is a human who signs in; a person is a human the
-- club has a relationship with. Most members are both, and they're linked
-- through people.user_id — but a user with no person row is fine (a district
-- admin), and a person with no user row is the common case (a guest, a donor).
CREATE TABLE users (
  id             TEXT PRIMARY KEY,
  email          TEXT NOT NULL,
  email_norm     TEXT NOT NULL UNIQUE,   -- lower(trim(email)); the real key
  display_name   TEXT,
  -- Password is optional: magic link is the primary path. NULL here means
  -- "this account has never set a password", which is not an error state.
  password_hash  TEXT,
  password_salt  TEXT,
  last_login_at  TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

-- Which tenants a user can reach, and with what baseline standing. Fine-grained
-- authority comes from role_assignments; this table answers "may they in at all".
CREATE TABLE tenant_users (
  tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status      TEXT NOT NULL DEFAULT 'active',  -- active | suspended
  created_at  TEXT NOT NULL,
  PRIMARY KEY (tenant_id, user_id)
);
CREATE INDEX idx_tenant_users_user ON tenant_users(user_id);

-- Session shadow. KV is the fast path for session lookup; this table exists so
-- "sign this person out everywhere, right now" is a single indexed DELETE and
-- so an admin can see active sessions. Revocation writes both places.
CREATE TABLE sessions (
  id          TEXT PRIMARY KEY,          -- session token id (not the secret)
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id   TEXT REFERENCES tenants(id) ON DELETE CASCADE,
  user_agent  TEXT,
  ip_hash     TEXT,
  expires_at  TEXT NOT NULL,
  created_at  TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- ── Federation shape ──────────────────────────────────────────────────────────
CREATE TABLE districts (
  id            TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  ri_number     TEXT,                -- Rotary International district number, e.g. "5950"
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL,
  zone          TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);
CREATE INDEX idx_districts_tenant ON districts(tenant_id);

CREATE TABLE clubs (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  district_id    TEXT REFERENCES districts(id) ON DELETE SET NULL,
  ri_number      TEXT,               -- Rotary International club id
  name           TEXT NOT NULL,
  slug           TEXT NOT NULL,
  club_type      TEXT NOT NULL DEFAULT 'rotary',  -- rotary | rotaract | interact | satellite
  charter_date   TEXT,               -- YYYY-MM-DD
  city           TEXT,
  state_code     TEXT,
  country_code   TEXT,
  timezone       TEXT,
  website_url    TEXT,
  -- Public page content. A club that never opens the editor still gets a real
  -- page from these defaults plus its meetings and projects.
  public_enabled INTEGER NOT NULL DEFAULT 1,
  public_blurb   TEXT,
  public_photo_key TEXT,             -- R2 object key
  meeting_blurb  TEXT,               -- "Thursdays at noon, Blue Water Grill"
  status         TEXT NOT NULL DEFAULT 'active',
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);
CREATE INDEX idx_clubs_tenant ON clubs(tenant_id);
CREATE INDEX idx_clubs_district ON clubs(district_id);
-- Public club pages resolve by slug across all tenants, so this lookup needs
-- its own global index — it is the one intentional cross-tenant read path.
CREATE UNIQUE INDEX idx_clubs_public_slug ON clubs(slug) WHERE public_enabled = 1;

-- ── People ────────────────────────────────────────────────────────────────────
-- A person is canonical within a tenant and is never duplicated per club. Their
-- relationship to each club lives in memberships. This is the modelling rule the
-- whole product rests on: a member who moves clubs keeps their history.
CREATE TABLE people (
  id               TEXT PRIMARY KEY,
  tenant_id        TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id          TEXT REFERENCES users(id) ON DELETE SET NULL,
  household_id     TEXT,
  first_name       TEXT NOT NULL,
  last_name        TEXT NOT NULL,
  preferred_name   TEXT,
  email            TEXT,
  email_norm       TEXT,
  phone            TEXT,
  -- Roles stack. A comma-list, not a table per relationship type: someone is
  -- routinely a member AND a donor AND a speaker AND a sponsor contact.
  roles            TEXT NOT NULL DEFAULT '',
  employer         TEXT,
  job_title        TEXT,
  classification   TEXT,             -- Rotary "classification" (vocational category)
  birthday         TEXT,             -- MM-DD; year is optional and often withheld
  joined_rotary_on TEXT,             -- YYYY-MM-DD, across all clubs — drives anniversaries
  photo_key        TEXT,
  city             TEXT,
  state_code       TEXT,
  notes            TEXT,
  do_not_email     INTEGER NOT NULL DEFAULT 0,
  slug             TEXT,
  deleted_at       TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);
CREATE INDEX idx_people_tenant ON people(tenant_id, deleted_at);
-- Keyset pagination over (last_name, first_name, id) — never OFFSET.
CREATE INDEX idx_people_name ON people(tenant_id, last_name, first_name, id);
CREATE INDEX idx_people_email ON people(tenant_id, email_norm);
CREATE UNIQUE INDEX idx_people_slug ON people(tenant_id, slug) WHERE slug IS NOT NULL;

CREATE TABLE households (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  address_line1 TEXT,
  address_line2 TEXT,
  city         TEXT,
  state_code   TEXT,
  postal_code  TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX idx_households_tenant ON households(tenant_id);

CREATE TABLE household_members (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  person_id    TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  relationship TEXT,                 -- spouse | partner | child | other
  created_at   TEXT NOT NULL,
  UNIQUE (household_id, person_id)
);
CREATE INDEX idx_household_members_person ON household_members(tenant_id, person_id);

-- Partner orgs, sponsors, employers, host venues.
CREATE TABLE organizations (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  kind         TEXT NOT NULL DEFAULT 'partner', -- partner | sponsor | venue | employer | nonprofit
  website_url  TEXT,
  city         TEXT,
  state_code   TEXT,
  notes        TEXT,
  slug         TEXT,
  deleted_at   TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX idx_orgs_tenant ON organizations(tenant_id, deleted_at);
CREATE INDEX idx_orgs_name ON organizations(tenant_id, name, id);

-- ── Membership lifecycle ──────────────────────────────────────────────────────
-- A membership is a relationship between a person and a club, not a status
-- column on the person. One person, several clubs, independent histories.
CREATE TABLE memberships (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id           TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id         TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  stage             TEXT NOT NULL DEFAULT 'lead',
  -- lead | guest_attended | in_conversation | invited_to_apply | candidate
  -- | approved | active | at_risk | leave_of_absence | resigned | alumni
  membership_type   TEXT NOT NULL DEFAULT 'active', -- active | honorary | corporate | satellite
  stage_entered_at  TEXT NOT NULL,
  joined_on         TEXT,            -- YYYY-MM-DD, this club specifically
  ended_on          TEXT,
  exit_reason       TEXT,            -- logged on resignation; the retention data nobody keeps
  exit_notes        TEXT,
  sponsor_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  mentor_person_id  TEXT REFERENCES people(id) ON DELETE SET NULL,
  referred_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  source            TEXT,            -- public_form | referral | manual | import | event
  is_primary_club   INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE (club_id, person_id)
);
CREATE INDEX idx_memberships_tenant ON memberships(tenant_id, stage);
CREATE INDEX idx_memberships_club ON memberships(club_id, stage);
CREATE INDEX idx_memberships_person ON memberships(tenant_id, person_id);
CREATE INDEX idx_memberships_stage_entered ON memberships(club_id, stage, stage_entered_at);

-- Append-only. The pipeline is reconstructable from this, which is how the
-- guest-to-member conversion report stays honest even after someone edits a stage.
CREATE TABLE membership_stage_events (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  membership_id  TEXT NOT NULL REFERENCES memberships(id) ON DELETE CASCADE,
  club_id        TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  from_stage     TEXT,
  to_stage       TEXT NOT NULL,
  reason         TEXT,
  actor_user_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  occurred_at    TEXT NOT NULL
);
CREATE INDEX idx_stage_events_membership ON membership_stage_events(membership_id, occurred_at);
CREATE INDEX idx_stage_events_club ON membership_stage_events(tenant_id, club_id, occurred_at);

-- ── Authority ─────────────────────────────────────────────────────────────────
-- Rotary titles are what people see; capabilities are what the server checks.
-- Assignments are scoped and time-bounded because Rotary leadership turns over
-- every July and last year's president should not still hold the keys.
CREATE TABLE role_assignments (
  id            TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  person_id     TEXT REFERENCES people(id) ON DELETE SET NULL,
  role_key      TEXT NOT NULL,       -- see domain/roles.ts — 'club_president', 'district_governor', …
  scope_type    TEXT NOT NULL,       -- tenant | district | club | committee
  scope_id      TEXT,                -- NULL when scope_type = 'tenant'
  -- Capabilities granted beyond the role's own bundle, comma-list. Lets a club
  -- hand its newsletter editor send rights without inventing a fake title.
  extra_caps    TEXT NOT NULL DEFAULT '',
  starts_on     TEXT,                -- YYYY-MM-DD, NULL = effective immediately
  ends_on       TEXT,                -- YYYY-MM-DD, NULL = open-ended
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_roles_user ON role_assignments(tenant_id, user_id);
CREATE INDEX idx_roles_scope ON role_assignments(tenant_id, scope_type, scope_id);

-- ── Meetings ──────────────────────────────────────────────────────────────────
CREATE TABLE meeting_series (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,           -- "Weekly Luncheon"
  rrule_weekday  INTEGER,                 -- 0=Sun … 6=Sat
  rrule_interval INTEGER NOT NULL DEFAULT 1,  -- every N weeks
  start_time     TEXT,                    -- "12:00"
  duration_min   INTEGER NOT NULL DEFAULT 60,
  location       TEXT,
  active         INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_series_club ON meeting_series(tenant_id, club_id, active);

CREATE TABLE meetings (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  series_id      TEXT REFERENCES meeting_series(id) ON DELETE SET NULL,
  title          TEXT,
  meeting_date   TEXT NOT NULL,           -- YYYY-MM-DD
  start_time     TEXT,
  location       TEXT,
  kind           TEXT NOT NULL DEFAULT 'regular', -- regular | board | social | service | district
  speaker_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  speaker_name   TEXT,                    -- for speakers who aren't a person record yet
  speaker_topic  TEXT,
  speaker_bio    TEXT,
  agenda         TEXT,
  notes          TEXT,
  recap          TEXT,                    -- AI may draft this; a human approves it
  recap_status   TEXT NOT NULL DEFAULT 'none', -- none | draft | approved
  meal_count     INTEGER,
  is_public      INTEGER NOT NULL DEFAULT 1,   -- shows on the public club page
  cancelled      INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_meetings_club_date ON meetings(tenant_id, club_id, meeting_date);
CREATE INDEX idx_meetings_upcoming ON meetings(club_id, meeting_date) WHERE cancelled = 0;

CREATE TABLE meeting_attendance (
  id            TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  meeting_id    TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id     TEXT REFERENCES people(id) ON DELETE CASCADE,
  guest_name    TEXT,                     -- walk-in guests with no record yet
  guest_email   TEXT,
  status        TEXT NOT NULL DEFAULT 'present',
  -- present | absent | excused | makeup | rsvp_yes | rsvp_no
  is_guest      INTEGER NOT NULL DEFAULT 0,
  host_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  makeup_note   TEXT,
  recorded_by   TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at    TEXT NOT NULL,
  UNIQUE (meeting_id, person_id)
);
CREATE INDEX idx_attendance_person ON meeting_attendance(tenant_id, person_id, created_at);
CREATE INDEX idx_attendance_meeting ON meeting_attendance(meeting_id, status);
CREATE INDEX idx_attendance_club ON meeting_attendance(club_id, created_at);

-- ── Committees & service projects ─────────────────────────────────────────────
CREATE TABLE committees (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id      TEXT REFERENCES clubs(id) ON DELETE CASCADE,  -- NULL = district committee
  district_id  TEXT REFERENCES districts(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  purpose      TEXT,
  goals        TEXT,
  meeting_rhythm TEXT,
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX idx_committees_tenant ON committees(tenant_id, active);
CREATE INDEX idx_committees_club ON committees(club_id, active);

CREATE TABLE committee_members (
  id            TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  committee_id  TEXT NOT NULL REFERENCES committees(id) ON DELETE CASCADE,
  person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  role          TEXT NOT NULL DEFAULT 'member',  -- chair | vice_chair | member
  starts_on     TEXT,
  ends_on       TEXT,
  created_at    TEXT NOT NULL,
  UNIQUE (committee_id, person_id)
);
CREATE INDEX idx_committee_members_person ON committee_members(tenant_id, person_id);

CREATE TABLE projects (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT REFERENCES clubs(id) ON DELETE SET NULL,
  district_id    TEXT REFERENCES districts(id) ON DELETE SET NULL,
  committee_id   TEXT REFERENCES committees(id) ON DELETE SET NULL,
  name           TEXT NOT NULL,
  slug           TEXT,
  summary        TEXT,
  description    TEXT,
  area_of_focus  TEXT,        -- Rotary's seven areas of focus
  status         TEXT NOT NULL DEFAULT 'planned', -- planned | active | complete | cancelled
  starts_on      TEXT,
  ends_on        TEXT,
  budget_cents   INTEGER NOT NULL DEFAULT 0,
  spent_cents    INTEGER NOT NULL DEFAULT 0,
  volunteer_slots INTEGER,
  people_served  INTEGER,
  outcome_notes  TEXT,
  photo_key      TEXT,
  is_public      INTEGER NOT NULL DEFAULT 1,
  -- Cross-club collaboration: a project can be shared with sibling clubs in the
  -- same tenant without duplicating the record.
  is_shared      INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_projects_tenant ON projects(tenant_id, status);
CREATE INDEX idx_projects_club ON projects(club_id, status);

CREATE TABLE project_participants (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id   TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  person_id    TEXT REFERENCES people(id) ON DELETE CASCADE,
  club_id      TEXT REFERENCES clubs(id) ON DELETE SET NULL,
  role         TEXT NOT NULL DEFAULT 'volunteer', -- lead | volunteer | partner
  signed_up_at TEXT,
  hours        REAL NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL,
  UNIQUE (project_id, person_id)
);
CREATE INDEX idx_project_participants_person ON project_participants(tenant_id, person_id);

CREATE TABLE project_partners (
  id              TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id      TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role            TEXT,
  created_at      TEXT NOT NULL,
  UNIQUE (project_id, organization_id)
);

-- ── Interactions, tasks, notes ────────────────────────────────────────────────
-- Append-only touchpoint spine. Every inbound action lands here: a call, an
-- email reply, a meeting attended, a stage move, a gift. Reports read from it,
-- signals are derived from it, and nothing edits it after the fact.
CREATE TABLE interactions (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT REFERENCES clubs(id) ON DELETE SET NULL,
  person_id      TEXT REFERENCES people(id) ON DELETE CASCADE,
  organization_id TEXT REFERENCES organizations(id) ON DELETE SET NULL,
  kind           TEXT NOT NULL,
  -- call | email_out | email_in | meeting | attendance | note | stage_change
  -- | gift | signup | rsvp | task_done | system
  source_module  TEXT NOT NULL DEFAULT 'app',
  subject        TEXT,
  body           TEXT,
  outcome        TEXT,             -- connected | no_response | follow_up | not_a_fit
  signal_weight  REAL NOT NULL DEFAULT 1,
  ref_type       TEXT,             -- meeting | project | membership | dues_invoice | …
  ref_id         TEXT,
  actor_user_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  is_private     INTEGER NOT NULL DEFAULT 0,
  occurred_at    TEXT NOT NULL,
  created_at     TEXT NOT NULL
);
CREATE INDEX idx_interactions_person ON interactions(tenant_id, person_id, occurred_at);
CREATE INDEX idx_interactions_club ON interactions(tenant_id, club_id, occurred_at);
CREATE INDEX idx_interactions_kind ON interactions(tenant_id, kind, occurred_at);

CREATE TABLE tasks (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT REFERENCES clubs(id) ON DELETE CASCADE,
  title          TEXT NOT NULL,
  details        TEXT,
  assignee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assignee_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  subject_person_id  TEXT REFERENCES people(id) ON DELETE CASCADE,
  ref_type       TEXT,
  ref_id         TEXT,
  due_on         TEXT,             -- YYYY-MM-DD
  status         TEXT NOT NULL DEFAULT 'open',  -- open | done | dismissed
  priority       TEXT NOT NULL DEFAULT 'normal',
  -- Set when a signal or automation created this, so we can measure whether
  -- the nudges actually lead anywhere.
  origin         TEXT NOT NULL DEFAULT 'manual', -- manual | signal | automation | import
  origin_ref     TEXT,
  completed_at   TEXT,
  created_by     TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_tasks_open ON tasks(tenant_id, status, due_on);
CREATE INDEX idx_tasks_assignee ON tasks(tenant_id, assignee_user_id, status);
CREATE INDEX idx_tasks_subject ON tasks(tenant_id, subject_person_id, status);

-- ── Dues, donations, payments ─────────────────────────────────────────────────
CREATE TABLE dues_invoices (
  id            TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  membership_id TEXT REFERENCES memberships(id) ON DELETE SET NULL,
  period_label  TEXT NOT NULL,       -- "2026-27 H1"
  amount_cents  INTEGER NOT NULL,
  paid_cents    INTEGER NOT NULL DEFAULT 0,
  due_on        TEXT,
  status        TEXT NOT NULL DEFAULT 'open', -- open | paid | partial | waived | void
  notes         TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_dues_club ON dues_invoices(tenant_id, club_id, status);
CREATE INDEX idx_dues_person ON dues_invoices(tenant_id, person_id, status);

CREATE TABLE payments (
  id             TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id        TEXT REFERENCES clubs(id) ON DELETE SET NULL,
  person_id      TEXT REFERENCES people(id) ON DELETE SET NULL,
  invoice_id     TEXT REFERENCES dues_invoices(id) ON DELETE SET NULL,
  kind           TEXT NOT NULL DEFAULT 'dues',  -- dues | donation | event | other
  amount_cents   INTEGER NOT NULL,
  fee_cents      INTEGER NOT NULL DEFAULT 0,
  covered_fee    INTEGER NOT NULL DEFAULT 0,    -- payer opted to cover processing
  method         TEXT NOT NULL DEFAULT 'manual', -- manual | stripe | check | cash
  external_id    TEXT,                          -- stripe payment intent
  received_on    TEXT NOT NULL,
  receipt_sent_at TEXT,
  notes          TEXT,
  created_at     TEXT NOT NULL,
  UNIQUE (tenant_id, method, external_id)
);
CREATE INDEX idx_payments_club ON payments(tenant_id, club_id, received_on);
CREATE INDEX idx_payments_person ON payments(tenant_id, person_id, received_on);

-- ── Tags ──────────────────────────────────────────────────────────────────────
CREATE TABLE tags (
  id          TEXT PRIMARY KEY,
  tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  label       TEXT NOT NULL,
  color       TEXT,
  created_at  TEXT NOT NULL,
  UNIQUE (tenant_id, label)
);

CREATE TABLE entity_tags (
  id          TEXT PRIMARY KEY,
  tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  tag_id      TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id   TEXT NOT NULL,
  created_at  TEXT NOT NULL,
  UNIQUE (tag_id, entity_type, entity_id)
);
CREATE INDEX idx_entity_tags_entity ON entity_tags(tenant_id, entity_type, entity_id);

-- ── Files ─────────────────────────────────────────────────────────────────────
CREATE TABLE files (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  r2_key       TEXT NOT NULL UNIQUE,
  filename     TEXT NOT NULL,
  content_type TEXT,
  size_bytes   INTEGER,
  entity_type  TEXT,
  entity_id    TEXT,
  is_public    INTEGER NOT NULL DEFAULT 0,
  uploaded_by  TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_files_entity ON files(tenant_id, entity_type, entity_id);

-- ── Invites ───────────────────────────────────────────────────────────────────
CREATE TABLE invites (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  club_id      TEXT REFERENCES clubs(id) ON DELETE CASCADE,
  email_norm   TEXT NOT NULL,
  person_id    TEXT REFERENCES people(id) ON DELETE SET NULL,
  role_key     TEXT NOT NULL DEFAULT 'member',
  token_hash   TEXT NOT NULL UNIQUE,   -- never store the token itself
  invited_by   TEXT REFERENCES users(id) ON DELETE SET NULL,
  expires_at   TEXT NOT NULL,
  accepted_at  TEXT,
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_invites_tenant ON invites(tenant_id, accepted_at);

-- ── Audit ─────────────────────────────────────────────────────────────────────
CREATE TABLE audit_log (
  id           TEXT PRIMARY KEY,
  tenant_id    TEXT REFERENCES tenants(id) ON DELETE CASCADE,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,
  entity_type  TEXT NOT NULL,
  entity_id    TEXT,
  entity_label TEXT,
  changes      TEXT,                  -- JSON
  ip_hash      TEXT,
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_audit_tenant ON audit_log(tenant_id, created_at);
CREATE INDEX idx_audit_entity ON audit_log(tenant_id, entity_type, entity_id);
