/**
 * gardener-campaign-import-csv — Imports a CSV of recipients for a Gardener-tracked
 * federation campaign (starting with Propria).
 *
 * WHAT: Parses CSV, validates emails, dedupes, and either previews (dry_run) or
 *       writes gardener_tracked_sends rows with sent_at=null (queue for send phase).
 * WHERE: Called from the Operator composer when the gardener enables federation
 *        tracking and drops a CSV file (typically generated by PerplexityAI).
 * WHY: Lets the operator import audiences per campaign without touching tenant tables.
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";
import { emailHash } from "../_shared/federationTracking.ts";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { ...CORS, "Content-Type": "application/json" } });
}

// RFC 4180-ish CSV parser (handles quoted fields with embedded commas, escaped quotes, CRLF)
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += c; i++; continue;
    }
    if (c === '"') { inQuotes = true; i++; continue; }
    if (c === ",") { row.push(field); field = ""; i++; continue; }
    if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; i++; continue; }
    if (c === "\r") { i++; continue; }
    field += c; i++;
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.some((f) => f.trim().length > 0));
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const KNOWN_COLS = new Set(["email", "name", "first_name", "last_name", "organization", "role", "city", "state", "notes"]);
const MAX_ROWS = 5000;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) return json({ error: "Unauthorized" }, 401);

    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const token = authHeader.replace("Bearer ", "");
    const { data: claims, error: claimErr } = await userClient.auth.getClaims(token);
    if (claimErr || !claims?.claims?.sub) return json({ error: "Unauthorized" }, 401);
    const userId = claims.claims.sub as string;

    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Gate on admin (operator/gardener) role
    const { data: roleRow } = await admin
      .from("user_roles")
      .select("role")
      .eq("user_id", userId)
      .eq("role", "admin")
      .maybeSingle();
    if (!roleRow) return json({ error: "Forbidden" }, 403);

    const body = await req.json().catch(() => null);
    if (!body) return json({ error: "Invalid JSON" }, 400);

    const campaignId = String(body.campaign_id || "");
    const federationAppSlug = String(body.federation_app_slug || "").toLowerCase();
    const csvBase64 = String(body.csv_base64 || "");
    const filename = body.filename ? String(body.filename) : null;
    const dryRun = body.dry_run === true;
    const disclosePixel = body.disclose_pixel !== false;

    if (!/^[0-9a-f-]{36}$/i.test(campaignId)) return json({ error: "campaign_id is required" }, 400);
    if (!federationAppSlug) return json({ error: "federation_app_slug is required" }, 400);
    if (!csvBase64) return json({ error: "csv_base64 is required" }, 400);

    // Validate campaign + federation app
    const { data: campaign } = await admin.from("email_campaigns").select("id, subject").eq("id", campaignId).maybeSingle();
    if (!campaign) return json({ error: "Campaign not found" }, 404);
    const { data: fedApp } = await admin.from("federation_apps").select("slug, name").eq("slug", federationAppSlug).maybeSingle();
    if (!fedApp) return json({ error: "Federation app not found" }, 404);

    // Decode CSV
    let csvText = "";
    try {
      const bin = atob(csvBase64);
      const bytes = Uint8Array.from(bin, (c) => c.charCodeAt(0));
      csvText = new TextDecoder("utf-8").decode(bytes);
    } catch {
      return json({ error: "Invalid csv_base64" }, 400);
    }
    if (csvText.length > 5 * 1024 * 1024) return json({ error: "CSV too large (max 5 MB)" }, 400);

    const rows = parseCsv(csvText);
    if (rows.length < 2) return json({ error: "CSV must have a header row and at least one data row" }, 400);

    const headers = rows[0].map((h) => h.trim().toLowerCase());
    const emailIdx = headers.indexOf("email");
    if (emailIdx === -1) return json({ error: "CSV must include an 'email' column" }, 400);

    const dataRows = rows.slice(1);
    if (dataRows.length > MAX_ROWS) return json({ error: `Too many rows (max ${MAX_ROWS})` }, 400);

    // Parse + validate + dedupe within CSV
    const seen = new Set<string>();
    const parsed: Array<{
      email: string;
      email_hash: string;
      name: string | null;
      metadata: Record<string, string>;
    }> = [];
    let invalid = 0;
    let dupedInCsv = 0;

    for (const r of dataRows) {
      const email = (r[emailIdx] || "").trim().toLowerCase();
      if (!email || !EMAIL_RE.test(email)) { invalid++; continue; }
      const hash = await emailHash(email);
      if (seen.has(hash)) { dupedInCsv++; continue; }
      seen.add(hash);

      const metadata: Record<string, string> = {};
      let firstName = "", lastName = "", fullName = "";
      headers.forEach((h, idx) => {
        if (idx === emailIdx) return;
        const val = (r[idx] || "").trim();
        if (!val) return;
        if (h === "name") fullName = val;
        else if (h === "first_name") firstName = val;
        else if (h === "last_name") lastName = val;
        if (KNOWN_COLS.has(h)) metadata[h] = val;
        else metadata[h] = val; // still preserve unknown columns
      });
      const name = fullName || [firstName, lastName].filter(Boolean).join(" ").trim() || null;
      parsed.push({ email, email_hash: hash, name, metadata });
    }

    // Existing tracked campaign?
    const { data: existingTc } = await admin
      .from("gardener_tracked_campaigns")
      .select("id, federation_app_slug")
      .eq("campaign_id", campaignId)
      .maybeSingle();

    let dupedAgainstExisting = 0;
    if (existingTc) {
      // Filter out already-imported recipients
      const hashes = parsed.map((p) => p.email_hash);
      if (hashes.length > 0) {
        const { data: existingSends } = await admin
          .from("gardener_tracked_sends")
          .select("recipient_email_hash")
          .eq("tracked_campaign_id", existingTc.id)
          .in("recipient_email_hash", hashes);
        const existingSet = new Set((existingSends || []).map((s: any) => s.recipient_email_hash));
        dupedAgainstExisting = existingSet.size;
        for (let i = parsed.length - 1; i >= 0; i--) {
          if (existingSet.has(parsed[i].email_hash)) parsed.splice(i, 1);
        }
      }
    }

    const preview = {
      rows_total: dataRows.length,
      rows_valid: parsed.length,
      rows_invalid: invalid,
      rows_duped_in_csv: dupedInCsv,
      rows_duped_against_existing: dupedAgainstExisting,
      sample: parsed.slice(0, 5).map((p) => ({ email: p.email, name: p.name, metadata: p.metadata })),
    };

    if (dryRun) return json({ ok: true, dry_run: true, preview });

    // Commit
    let tcId = existingTc?.id;
    if (!tcId) {
      const { data: tcNew, error: tcErr } = await admin
        .from("gardener_tracked_campaigns")
        .insert({
          campaign_id: campaignId,
          federation_app_slug: federationAppSlug,
          gardener_user_id: userId,
          tracking_enabled: true,
          disclose_pixel: disclosePixel,
          csv_import_filename: filename,
          csv_row_count: parsed.length,
        })
        .select("id")
        .single();
      if (tcErr) return json({ error: "Failed to create tracked campaign", details: tcErr.message }, 500);
      tcId = tcNew.id;

      // Link the campaign to the federation app for filtering later
      await admin.from("email_campaigns").update({ federation_app_slug: federationAppSlug }).eq("id", campaignId);
    } else {
      await admin
        .from("gardener_tracked_campaigns")
        .update({
          csv_import_filename: filename,
          csv_row_count: (existingTc as any).csv_row_count ? (existingTc as any).csv_row_count + parsed.length : parsed.length,
          disclose_pixel: disclosePixel,
        })
        .eq("id", tcId);
    }

    // Insert sends in batches of 500
    const inserts = parsed.map((p) => ({
      tracked_campaign_id: tcId,
      recipient_email: p.email,
      recipient_email_hash: p.email_hash,
      recipient_name: p.name,
      recipient_metadata: p.metadata,
      subject: campaign.subject ?? null,
    }));

    let inserted = 0;
    for (let i = 0; i < inserts.length; i += 500) {
      const chunk = inserts.slice(i, i + 500);
      const { error: insErr, count } = await admin
        .from("gardener_tracked_sends")
        .insert(chunk, { count: "exact" });
      if (insErr) {
        console.error("insert error:", insErr);
        return json({ error: "Failed to insert recipients", details: insErr.message, inserted }, 500);
      }
      inserted += count ?? chunk.length;
    }

    return json({
      ok: true,
      dry_run: false,
      preview,
      tracked_campaign_id: tcId,
      inserted,
    });
  } catch (e) {
    console.error("gardener-campaign-import-csv error:", e);
    return json({ error: "Server error", details: String(e) }, 500);
  }
});
